package peddi.adftutorial.demo.model.service.client;

import java.util.HashMap;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import peddi.adftutorial.demo.model.service.common.HRSystemAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 13 15:40:46 BST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRSystemAMClient extends ApplicationModuleImpl implements HRSystemAM {
    /**
     * This is the default constructor (do not remove).
     */
    public HRSystemAMClient() {
    }

    public void populateCheckNListVO1(HashMap selectedValues) {
        Object _ret = this.riInvokeExportedMethod(this,"populateCheckNListVO1",new String [] {"java.util.HashMap"},new Object[] {selectedValues});
        return;
    }
}
