package peddi.adftutorial.demo.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 31 23:23:05 BST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesEODefImpl() {
    }
}
