package peddi.adftutorial.demo.model.view;

import java.sql.ResultSet;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaManager;
import oracle.jbo.common.ViewCriteriaManagerOwner;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;

import peddi.adftutorial.demo.model.view.common.EmloyeesVOViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 07 11:42:36 BST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmloyeesVOViewCriteriaImpl extends ViewObjectImpl implements EmloyeesVOViewCriteria {
    /**
     * This is the default constructor (do not remove).
     */
    public EmloyeesVOViewCriteriaImpl() {
    }

    /**
     * Returns the variable value for DepartmentID.
     * @return variable value for DepartmentID
     */
    public String getDeptID() {
        return (String)ensureVariableManager().getVariableValue("DeptID");
    }

    /**
     * Sets <code>value</code> for variable DepartmentID.
     * @param value value to bind as DepartmentID
     */
    public void setDeptID(String value) {
        ensureVariableManager().setVariableValue("DeptID", value);
    }

    /**
     * Returns the variable value for SalaryGT.
     * @return variable value for SalaryGT
     */
    public String getSalaryGT() {
        return (String)ensureVariableManager().getVariableValue("SalaryGT");
    }

    /**
     * Sets <code>value</code> for variable SalaryGT.
     * @param value value to bind as SalaryGT
     */
    public void setSalaryGT(String value) {
        ensureVariableManager().setVariableValue("SalaryGT", value);
    }

    /**
     * @param pDeptName Department Name in String
     */
    public void showEmpFromDept(String pDeptName){
        //this.clearViewCriterias();
        ViewCriteriaManager vcMgr = this.getViewCriteriaManager();
        ViewCriteria vcEmpDept = vcMgr.getViewCriteria("EmpDeptCriteria");
        if ("Shipping".equalsIgnoreCase(pDeptName)){
            vcEmpDept.ensureVariableManager().setVariableValue("DeptID", "50");
        }
        else if("IT".equalsIgnoreCase(pDeptName)){
            vcEmpDept.ensureVariableManager().setVariableValue("DeptID", "60");
        }
        setApplyViewCriteriaName("EmpDeptCriteria");
        this.executeQuery();
    }


}
