package peddi.adftutorial.demo.model.service.common;

import java.util.HashMap;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 13 15:40:46 BST 2013
// ---------------------------------------------------------------------
public interface HRSystemAM extends ApplicationModule {
    void populateCheckNListVO1(HashMap selectedValues);
}
