package peddi.adftutorial.demo.model.view.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import peddi.adftutorial.demo.model.view.common.EmloyeesVOViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 07 12:15:28 BST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmloyeesVOViewCriteriaClient extends ViewUsageImpl implements EmloyeesVOViewCriteria {
    /**
     * This is the default constructor (do not remove).
     */
    public EmloyeesVOViewCriteriaClient() {
    }

    public void showEmpFromDept(String pDeptName) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"showEmpFromDept",new String [] {"java.lang.String"},new Object[] {pDeptName});
        return;
    }
}
