package peddi.adftutorial.demo.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 07 12:15:27 BST 2013
// ---------------------------------------------------------------------
public interface EmloyeesVOViewCriteria extends ViewObject {
    void showEmpFromDept(String pDeptName);
}
