package peddi.adftutorial.demo.model.service;

import java.util.HashMap;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import peddi.adftutorial.demo.model.service.common.HRSystemAM;
import peddi.adftutorial.demo.model.view.EmloyeesVOViewCriteriaImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 19 17:34:19 BST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRSystemAMImpl extends ApplicationModuleImpl implements HRSystemAM {
    /**
     * This is the default constructor (do not remove).
     */
    public HRSystemAMImpl() {
    }

    /**
     * Container's getter for DepartmentsVO1.
     * @return DepartmentsVO1
     */
    public ViewObjectImpl getDepartmentsVO1() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO1");
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public ViewObjectImpl getEmployeesVO1() {
        return (ViewObjectImpl)findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for JobsVO1.
     * @return JobsVO1
     */
    public ViewObjectImpl getJobsVO1() {
        return (ViewObjectImpl)findViewObject("JobsVO1");
    }

    /**
     * Container's getter for EmployeesVO2.
     * @return EmployeesVO2
     */
    public ViewObjectImpl getEmployeesVO2() {
        return (ViewObjectImpl)findViewObject("EmployeesVO2");
    }

    /**
     * Container's getter for EmployeesVO3.
     * @return EmployeesVO3
     */
    public ViewObjectImpl getEmployeesVO3() {
        return (ViewObjectImpl)findViewObject("EmployeesVO3");
    }

    /**
     * Container's getter for DepartmentsVO2.
     * @return DepartmentsVO2
     */
    public ViewObjectImpl getDepartmentsVO2() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO2");
    }

    /**
     * Container's getter for EmpDetailsVO1.
     * @return EmpDetailsVO1
     */
    public ViewObjectImpl getEmpDetailsVO1() {
        return (ViewObjectImpl)findViewObject("EmpDetailsVO1");
    }

    /**
     * Container's getter for EmpByEmailVO1.
     * @return EmpByEmailVO1
     */
    public ViewObjectImpl getEmpByEmailVO1() {
        return (ViewObjectImpl)findViewObject("EmpByEmailVO1");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptMgrFkLink1");
    }
    public void printPeddi(){
        System.out.println("Hi Peddi");
    }

    /**
     * Container's getter for EmployeeVOBindVariables1.
     * @return EmployeeVOBindVariables1
     */
    public ViewObjectImpl getEmployeeVOBindVariables1() {
        return (ViewObjectImpl)findViewObject("EmployeeVOBindVariables1");
    }

    /**
     * Container's getter for EmloyeesVOViewCriteria1.
     * @return EmloyeesVOViewCriteria1
     */
    public ViewObjectImpl getEmloyeesVOViewCriteria1() {
        return (ViewObjectImpl)findViewObject("EmloyeesVOViewCriteria1");
    }

    /**
     * Container's getter for CheckNListVO1.
     * @return CheckNListVO1
     */
    public ViewObjectImpl getCheckNListVO1() {
        return (ViewObjectImpl)findViewObject("CheckNListVO1");
    }
    public void populateCheckNListVO1(HashMap selectedValues){
        ViewObjectImpl vo = getCheckNListVO1();
        vo.reset();
        vo.clearCache();
        
        
        System.out.println(selectedValues.get("SelectOneChoice"));
        System.out.println(selectedValues.get("SelectManyChoice"));
        System.out.println(selectedValues.get("SelectBoolChkBox"));
        System.out.println(selectedValues.get("SelectManyChkBox"));
        System.out.println(selectedValues.get("SelectOneListBox"));
        System.out.println(selectedValues.get("SelectManyListBox"));
        System.out.println(selectedValues.get("SelectOneRadio"));
        System.out.println(selectedValues.get("SelectBoolRadio"));
        
        Row row = vo.createRow();
        row.setAttribute("SelectOneChoice", selectedValues.get("SelectOneChoice"));
        row.setAttribute("SelectManyChoice", selectedValues.get("SelectManyChoice"));
        row.setAttribute("SelectBoolChkBox", selectedValues.get("SelectBoolChkBox"));
        row.setAttribute("SelectManyChkBox", selectedValues.get("SelectManyChkBox"));
        row.setAttribute("SelectOneListBox", selectedValues.get("SelectOneListBox"));
        row.setAttribute("SelectManyListBox", selectedValues.get("SelectManyListBox"));
        row.setAttribute("SelectOneRadio", selectedValues.get("SelectOneRadio"));
        row.setAttribute("SelectBoolRadio", selectedValues.get("SelectBoolRadio"));
        vo.insertRow(row);
    }
}
